class Library():
    def __init__(self, list_of_books, Library_name):
        # dictionary for all books keys
        self.lend_data = {}
        self.list_of_books = list_of_books
        self.library_name = Library_name

        # adding books to dictionary
        for books in self.list_of_books:
            # none means No author have lend this book
            self.lend_data[books] = None

    def display_books(self):
        for index, books in enumerate(self.list_of_books):
            print(f"{index}){books}")

    def lend_book(self, book, author):
        if book in self.list_of_books:
            if self.lend_data[book] is None:
                self.lend_data[book] = author
            else:
                print(f"Sorry This book is lend by {self.lend_data[book]}")
        else:
            print("You have written wrong book name")

    def return_book(self, book,
                    author):
        if book in self.list_of_books:
            if self.lend_data[book] is not None:
                self.lend_data.pop(book)
            else:
                print("Sorry but This book is not Lend")
        else:
            print("You have written wrong book name")

    def add_book(self, book_name):
        self.list_of_books.append(book_name)
        self.lend_data[book_name] = None

    def delete_book(self, book_name):
        self.list_of_books.remove(book_name)
        self.lend_data.pop(book_name)


def main():
    # By deafault variables
    list_books = ['Introduction to Algorithms','Sherlock Holmes', 'The C programming', 'Rich Dad and Poor Dad','The Art of programming','Artificial Intelligence','The Mythical man','Clean code',
                  'Introduction to Automata','Computer networks','Data Strucures']
    Library_name = 'The_Ambition'
    secret_key = 423456

    The_Ambition = Library(list_books, Library_name)

    print(
        f"Welecome To {The_Ambition.library_name} library\nQ for exit \nTo Display Books press 'D'\nTo Lend a Book press 'L' \nReturn a Book press 'R' \nTo Add Book press 'A'and To Delete Book press 'DEL'\n ")

    Exit = False
    while (Exit is not True):
        _input = input("OPTION:")

        if _input == "Q":
            Exit = True

        elif _input == "D":
            The_Ambition.display_books()

        elif _input == "L":
            input2 = input("What is your name:")
            input3 = input("Which Book Do you want to lend:")
            print("\nBook Lend")
            The_Ambition.lend_book(input3, input2)

        elif _input == "A":
            input2 = input("Book name:")
            The_Ambition.add_book(input2)

        elif _input == "DEL":
            _input_secret = int(input("Write the secret key to delete:"))
            if (_input_secret == secret_key):
                input2 = input("Which Book do you want to delete:")
                The_Ambition.delete_book(input2)
            else:
                print("Sorry We can't Delete this Book")

        elif _input == "R":
            input2 = input("What is your name:")
            input3 = input("Which Book Do you want to return:")
            The_Ambition.return_book(input3, input2)


if __name__ == "__main__":
    main()
